name: sra
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - curl=7.78.0
  - hdf5=1.10.6
  - icu=68.1
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libcurl=7.78.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.1.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=11.1.0
  - libiconv=1.16
  - libnghttp2=1.43.0
  - libssh2=1.9.0
  - libstdcxx-ng=11.1.0
  - libxml2=2.9.12
  - ncbi-ngs-sdk=2.11.0
  - ncurses=6.2
  - openssl=1.1.1k
  - ossuuid=1.6.2
  - parallel-fastq-dump=0.6.7
  - perl=5.26.2
  - perl-app-cpanminus=1.7044
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-encode=2.88
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.36
  - perl-file-path=2.16
  - perl-file-temp=0.2304
  - perl-mime-base64=3.15
  - perl-parent=0.236
  - perl-uri=1.76
  - perl-xml-libxml=2.0132
  - perl-xml-namespacesupport=1.12
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xsloader=0.24
  - pigz=2.6
  - pip=21.2.1
  - python=3.9.6
  - python_abi=3.9
  - readline=8.1
  - setuptools=49.6.0
  - sqlite=3.36.0
  - sra-tools=2.11.0
  - tk=8.6.10
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
